### PR TITLE
linux related fixes + multiversion map read from nicolas-f

### PR DESCRIPTION
**Pull request by palmic**

### CODE REVIEW

**Comment by Ketchu13** [comment]
Thank for your contributions.

K13

**Comment by palmic** [comment]
Pleasure :-)
Unfortunatelly /addpoi erase all previous POIs before add one..
Iam not python guy, so to fix it myself it would require some advanced
debugging, i think it cant read old XML data successfully..

Have a nice day and thanks for the whole project, its awesome.
Best,
Michal.

**Comment by Ketchu13** [comment]
Hello, I have pushed a fix.
Please, feel you free to try the last version of this project.

Regards,
K13

**Comment by palmic** [comment]
awesome! Thank you very much.
Michal.

**Comment by palmic** [comment]
Hi Nicolas,

i found another bug with app multithreading - it spawned multiple threads and it wrote everything more than once - you can see it even [in your master](https://github.com/Ketchu13/7DTD-leaflet/commit/8bc96e6869ea916ef05d583a98031ed351564849).

I managed to worked-around a little - now in my branch it spawned only 2 threads and one from them looks like it cannot read POIwhitelist.xml, so it finally writes just one POI per message, but it respondes twice now - one with success (green message) and one with failure (the red one).

As i said before, this is my first python coding, so i really dont know how to fix it for good, so ill just leave it this way, because i can use it now without problem.

Thanks for the project again.
Michal.

**Comment by Ketchu13** [comment]
Hi,
Can you say me please, if you use the Gui version or the other ?
I don't have bug with the GUI version. I will check ALL versions tomorrow, and watch yours too.
Thanks again for your reports and your helps.

Regards,
K13
Edit: -check headless version + check ALL versions

**Comment by Ketchu13** [comment]
HI,
Finaly I have just checked the version whitout GUI and I don't any issue too, with this version for adding poi and tracks players positions.
(if you look in my last tracks.csv, yes all positions are same because I was static in game. No move.)
(Players positions is checked every 59 s)

Regards,
K13

**Comment by palmic** [comment]
Hi,
unfortunately i have these issues every time i use it (maybe its because i use it on linux - debian 7 wheezy x64).

I use only non gui version.
- app starts in more threads and do everything multiple times in parallel.
- app spawns more and more threads in time and by the time (maybe 1-2hours) 7dtd server stops working like it should (you cannot open chests for instance and when you disconnect, you cannot reconnect again till restart) (i think its glutted by that multiple threads connections)
- when you start the app in shell you cannot stop it in standard fashion by ctrl+C, so i start it in screen which i can terminate from outside.
- it wrote POIs multiple times before my hack (still its not solution), interestingly position seems to be written only once.

Unfortunately i have not enough time right now to learn Python so much it would deserve, but i gladly helped and i really thank you i can use the app.

Michal.

**Comment by Ketchu13** [comment]
Hi,
So, can you say me please, if you run/use the mapReader.py script with arguments in terminal or if you use the config file config.kfp ?
If you want to exit a python script just use Ctrl+Break . 

K13

**Comment by palmic** [comment]
Hi,
i use combination of parameters and config.
From shell i use parameters -g and -t and -v, anything other i let script to read from config.

Ill clone my virtual server today at evening and let you in to check at your own if you want, it will be much better.

**Comment by palmic** [comment]
Hi Nicolas,
as i said, i prepared debug environment for you on my server.
Its, clonned and prepared for you, so you can even destroy it from shell, never mind, its your sandbox now.

You should be able to connect it from ssh terminal this way:

```
ssh ketchu13@178.77.239.125
password is: leaflet
```

dont do anything under user ketchu13, just call su with the same password and you should find yourself in 7DTD-leaflet root, so you can start it by:

```
python ./map_reader.py -c "." -g "/home/sdtd/instances/palmic/Random Gen/3f6da7bdbbbe576a97ab530d30f2f2d1/Player" -v True
```

7d server is already running, you can check it this way:

```
7dtd.sh instances list
```

Its linux 7d server from here https://7dtd.illy.bz/ you can find instances management commands if you want create one from scratch or so.. its up to you.
You can even connect to already running palmic instance from your 7d game on the same IP with:

```
port: 26920
password: leaflet
```

You can use there following applications how do you want:
- mc (midnight commander)
- vim
- htop
- screen
  .. or you can of course install your own with root privileges, just use apt-get, or aptitude how do you want.

To manage your code just use copy+paste, scp or add your git origin into that repository and manage it by git fetch.. (my favourite)

Many thanks for your time,
Michal.

**Comment by Ketchu13** [comment]
Hi Michal,

Please take a look at the last pushed version of this project.
I did not have, yet , the time for upload the project on your server and test it.
Free for you to do it if you have more free time than me. (Maybe more later tonight)

Regards,
Ketchu13,

**Comment by Ketchu13** [comment]
I just found a new bug.. with the poilist.. A fix will be released soon

**Comment by palmic** [comment]
Hi,
Thanks for the info, just let me know if you'll need to upload some new version on server.
I would just call this for download your last master:

```
git remote //to check if there is not your remote present
git remote add ketchu13 git@github.com:Ketchu13/7DTD-leaflet.git
git fetch ketchu13
git checkout ketchu13/master
```

**Comment by palmic** [comment]
i've checkouted your actual master on the server, i've not tried it yet, because of your future fix.
best regards.

**Comment by Ketchu13** [comment]
The actual master work fine now on windows, you can check it out on linux if you want.

**Comment by palmic** [comment]
Thanks,
unfortunately i have still the same problems.
When i write first POI, it responds i have not record in whitelist (while i have one), but POI was writen.
It second try, it tries to write POI 2x (and responds 2x that i have not privileges to write POIs). POI is then writen 2x.

**Comment by palmic** [comment]
You can try it for yourself, just start your 7d game and connect to:

```
178.77.239.125
port: 26920
```

Just try to write some pois..

**Comment by Ketchu13** [comment]
I have tried to edit py scripts, with vim on your server, but I have some issues with the indenting.
I will install a "virtual" Debian soon for debug this project under linux. .

**Comment by Ketchu13** [comment]
capture d ecran1kde
As you can see, the map_reader + addpoi have no issue on this Debian 64Bits.

**Comment by palmic** [comment]
Hmm thats strange.
Ok than, thank you very much for your time and project.
Michal.

**Comment by Ketchu13** [comment]
Hi Michal,
I have some trouble with Git tonight.. 
Take a look at the branch named palmic in my repository please.
And say me if it's ok for you.

Regards,
k13

**Comment by palmic** [comment]
OK,
i will try it today about between 16:00 - 18:00 UTC.

I was wondering if your virtual debian had no multithreading problems just because you had not it running with multithreading supported, it has to be properly installed and set in virtual machine options.
- I had still the same problems on your previous version of nogui - new threads was spawned in time and after about 5 minutes i had 5+ threads listening and multiply-responses to /addpoi.

So i'll check your "palmic" branch today.
Thank you very much!

**Comment by Ketchu13** [comment]
Hi Michal,
It's nothing.

Let me show you the virtual machine cpu config and others screens of the master branch running under debian 64b with 4 cores
capture d ecran2kde
capture d ecran 2015-08-20 13 08 14
capture d ecran5kde
As you can see only 4 threads are running for map_reader+poi.
So only one answer =>
capture d ecran 2015-08-20 01 29 10

**Comment by Ketchu13** [comment]
I need to try this version on a linux Allocs server.
I have tested only on a windows 7dtd server but I don't think it's the principal issue..

**Comment by palmic** [comment]
Maybe its something about handling threads in Python on windows VS linux, but thats too advanced for me, if you know someone who is used to code python under linux, he should know whats the problem.

That my fixes are only tries based on some basic articles about threads and their syncing in python.
I believe there is some issue in that app about syncing the threads, because it spawns more and more in time, maybe every request from telnet, i dont know..

I still did not check that your palmic branch, so lets see this evening..

**Comment by palmic** [comment]
Hi Ketchu.
I tried your branch palmic now and everything seems to be ok now, thank you again!

**Comment by Ketchu13** [comment]
Hi Michal,
Happy to read that ! Let me know if you want more than just add poi on the map
 (ex: http://81.65.206.12:8081/index_cgi.html   it's just an example, locations of items are saved for an other map) . 

Regards,
k13

**Comment by palmic** [comment]
Nice! thanks.
Right now i would like 2 things:
- more icons to POIs controlled like /addpoi type message (type could be storage, base, ...)
- javascript autorefresh to map data, to have ability to view up to date data with keeping my viewport and zoom as is.

I could do that js refresh when i find some time for it.
Maybe i could add even that POI types i think it should be just simple regular expression to /addpoi message..

Have a nice evening.
Michal.

**Comment by Ketchu13** [comment]
Hi Michal, 
it's nothing, a pleasure.

I will improve the script, cause at the moment there are no queue system for generate the map tiles of this player.

So if a player left the game,  the map_reader does his job but if another player left the game at same location (so same map tiles) or at just before the end of the first generation , some display bugs can be raise(some tiles can be displayed only at various zoom level due to file acces).

Regards,
K13

**Comment by palmic** [comment]
ok, thanks for the info.
Michal.

**Pull request merged**
